sequenceDiagram
  participant participant_assertStaticImportBinding as assertStaticImportBinding
  participant participant_defineCustomNavigatorRegistry as defineCustomNavigatorRegistry
  participant_defineCustomNavigatorRegistry->>participant_assertStaticImportBinding: assertStaticImportBinding()
  participant_assertStaticImportBinding-->>participant_defineCustomNavigatorRegistry: return
