sequenceDiagram
  participant participant_assertModuleBinding as assertModuleBinding
  participant participant_defineCustomNavigatorRegistry as defineCustomNavigatorRegistry
  participant_defineCustomNavigatorRegistry->>participant_assertModuleBinding: assertModuleBinding()
  participant_assertModuleBinding-->>participant_defineCustomNavigatorRegistry: return
