graph TD
  package__ankhorage_zora_navigation["ZORA Navigation"]
  entrypoint_src_index_ts["src/index.ts"]
  package__ankhorage_zora_navigation --> entrypoint_src_index_ts
  module_src_index_ts["src/index.ts"]
