/** Explicit package entrypoint; implementation modules each own one export. */
export type { CustomNavigatorConfigIssue } from './features/custom/domain/CustomNavigatorConfigIssue';
export type { CustomNavigatorRegistration } from './features/custom/domain/CustomNavigatorRegistration';
export type { CustomNavigatorRegistry } from './features/custom/domain/CustomNavigatorRegistry';
export { defineCustomNavigatorRegistry } from './features/custom/domain/defineCustomNavigatorRegistry';
export { resolveTabsNavigatorPlan } from './features/tabs/application/resolveTabsNavigatorPlan';
export { resolveCustomTabsPresentation } from './features/tabs/domain/resolveCustomTabsPresentation';
export type { ResolvedCustomTabsPresentation } from './features/tabs/domain/ResolvedCustomTabsPresentation';
export type { ResolvedTabsImplementation } from './features/tabs/domain/ResolvedTabsImplementation';
export type { ResolvedTabsPresentation } from './features/tabs/domain/ResolvedTabsPresentation';
export type { TabsNavigatorPlan } from './features/tabs/domain/TabsNavigatorPlan';
export { createNavigatorPlan } from './utils/createNavigatorPlan';
export type { CreateNavigatorPlanOptions } from './utils/CreateNavigatorPlanOptions';
export type { ExpoRouterNavigatorModule } from './utils/ExpoRouterNavigatorModule';
export { generateNavigatorFiles } from './utils/generateNavigatorFiles';
export type { NavigatorAdapterId } from './utils/NavigatorAdapterId';
export type { NavigatorAdapterPlan } from './utils/NavigatorAdapterPlan';
export type { NavigatorApiStability } from './utils/NavigatorApiStability';
export type { NavigatorDiagnostic } from './utils/NavigatorDiagnostic';
export type { NavigatorGeneratedFile } from './utils/NavigatorGeneratedFile';
export type { NavigatorGenerationBindings } from './utils/NavigatorGenerationBindings';
export type { NavigatorGenerationOptions } from './utils/NavigatorGenerationOptions';
export type { NavigatorNodePlan } from './utils/NavigatorNodePlan';
export type { NavigatorPlan } from './utils/NavigatorPlan';
export type { NavigatorResponsiveSize } from './utils/NavigatorResponsiveSize';
export type { NavigatorRoutePlan } from './utils/NavigatorRoutePlan';
export type { NavigatorRuntimePlatform } from './utils/NavigatorRuntimePlatform';
export type { NavigatorScreenModule } from './utils/NavigatorScreenModule';
export type { NavigatorSupportStatus } from './utils/NavigatorSupportStatus';
export type { NavigatorValidationContext } from './utils/NavigatorValidationContext';
export { resolveNavigatorPreset } from './utils/resolveNavigatorPreset';
export { validateNavigatorManifest } from './utils/validateNavigatorManifest';
